// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package sqlc

import (
	"encoding/json"
	"time"
)

type JsonTable struct {
	ID       int32
	JsonData json.RawMessage
}

type Todo struct {
	ID        int32
	UserID    int32
	Text      string
	Done      bool
	CreatedAt time.Time
}

type User struct {
	ID        int32
	Name      string
	CreatedAt time.Time
}
