// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type JSONTable struct {
	ID       string `json:"id"`
	JSONData string `json:"jsonData"`
}

type NewTodo struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

type NewUser struct {
	Name string `json:"name"`
}
